### ISSUE TITLE
Some data makes chart scale weirdly

### ISSUE THREAD

**Issue by TimDaub** [attestate/svg-line-chart#23]
## Scope

- We want svg-line-chart to capture all necessary information of price over a period of time
- However, it seems like that for data set tickers like TACWHA-52/EUR or TREPEL-36/EUR, the chart doesn't scale well on the vertical price axis.
- E.g. for TACWHA-52/EUR it'd be sufficient to scale between 0-14 EUR but the scale goes beyond 35 EUR

<img width="944" alt="Screen Shot 2021-10-18 at 16 20 16" src="https://user-images.githubusercontent.com/2758453/137749628-631cdf78-bf1b-43c9-a2a9-9a2ef27df2e7.png">
<img width="939" alt="Screen Shot 2021-10-18 at 16 20 30" src="https://user-images.githubusercontent.com/2758453/137749638-ae89f395-6b44-4ace-9d1b-c4b7e5832e7f.png">

## Deliverables

- Write a unit test to cover the bug
- Find out what causes the error and propose a minimal solution

## Note

rugpullindex.com currently uses "svg-line-chart: 0.3.0". Please make sure you understand if the problem also happens on the current master etc.

**Comment by il3ven** [comment]
This looks like the `margin` property on the svg-line-chart is fixed for all charts. To get to the root of the problem I need the data that is used to plot these charts.

**Comment by TimDaub** [comment]
actually to address this issue properly: Do you think it'd make sense to give developers the option of defining an RPI API key to retrieve the data from the historical price api end point? With that, we'd make debugging more independent? We'd handle that in a separate issue though. Do you want to create it?

**Comment by il3ven** [comment]
Do you mean to integrate the API into this repo? So we only have to define a date and token.

**Comment by TimDaub** [comment]
yes

**Comment by il3ven** [comment]
That'll help. I'll make an issue. Should that one be picked up before this?

**Comment by TimDaub** [comment]
> Should that one be picked up before this?

yes

> That'll help. I'll make an issue.

thanks
